export const usedLettersArray = [
  { letter: 'Q', status: 'unknown' },
  { letter: 'W', status: 'unknown' },
  { letter: 'E', status: 'unknown' },
  { letter: 'R', status: 'unknown' },
  { letter: 'T', status: 'unknown' },
  { letter: 'Y', status: 'unknown' },
  { letter: 'U', status: 'unknown' },
  { letter: 'I', status: 'unknown' },
  { letter: 'O', status: 'unknown' },
  { letter: 'P', status: 'unknown' },
  { letter: 'A', status: 'unknown' },
  { letter: 'S', status: 'unknown' },
  { letter: 'D', status: 'unknown' },
  { letter: 'F', status: 'unknown' },
  { letter: 'G', status: 'unknown' },
  { letter: 'H', status: 'unknown' },
  { letter: 'J', status: 'unknown' },
  { letter: 'K', status: 'unknown' },
  { letter: 'L', status: 'unknown' },
  { letter: 'Z', status: 'unknown' },
  { letter: 'X', status: 'unknown' },
  { letter: 'C', status: 'unknown' },
  { letter: 'V', status: 'unknown' },
  { letter: 'B', status: 'unknown' },
  { letter: 'N', status: 'unknown' },
  { letter: 'M', status: 'unknown' },
]
